### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat-aem-tests#1]
Pl, update the readme file with proper execution steps.

Dependency error:
Testing started at 3:13 PM ...
3:13:16 PM: Executing task 'test'...

> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.cognifide.qa.bb:bb-core:2.0.0-SNAPSHOT.
  Searched in the following locations:
      file:/Users//.m2/repository/com/cognifide/qa/bb/bb-core/2.0.0-SNAPSHOT/maven-metadata.xml
      file:/Users//.m2/repository/com/cognifide/qa/bb/bb-core/2.0.0-SNAPSHOT/bb-core-2.0.0-SNAPSHOT.pom
      file:/Users//.m2/repository/com/cognifide/qa/bb/bb-core/2.0.0-SNAPSHOT/bb-core-2.0.0-SNAPSHOT.jar
      https://repo.maven.apache.org/maven2/com/cognifide/qa/bb/bb-core/2.0.0-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/com/cognifide/qa/bb/bb-core/2.0.0-SNAPSHOT/bb-core-2.0.0-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/com/cognifide/qa/bb/bb-core/2.0.0-SNAPSHOT/bb-core-2.0.0-SNAPSHOT.jar
  Required by:
      project :
> Could not find com.cognifide.qa.bb:bb-junit5:2.0.0-SNAPSHOT.
  Searched in the following locations:
      file:/Users//.m2/repository/com/cognifide/qa/bb/bb-junit5/2.0.0-SNAPSHOT/maven-metadata.xml
      file:/Users//.m2/repository/com/cognifide/qa/bb/bb-junit5/2.0.0-SNAPSHOT/bb-junit5-2.0.0-SNAPSHOT.pom
      file:/Users//.m2/repository/com/cognifide/qa/bb/bb-junit5/2.0.0-SNAPSHOT/bb-junit5-2.0.0-SNAPSHOT.jar

**Comment by Shaihuludus** [comment]
Hi, 
These tests are still in development for new bobcat 2.0. They should compile with branch 2.0.0-develop of bobcat. However they can still change because new AEM Authoring  Tests API is also in development

**Comment by DeChrish** [comment]
@Shaihuludus Thanks. How can I get early access to these test? I am in R/D team and constantly advocating bobcat 2.0. Pl let me know the minimal setup to proceed further.

**Comment by Shaihuludus** [comment]
You can checkout branch 2.0.0-develop from bobcat repository and build it.  Tests from this repository should work with such build. 

If You are interested in new API then new modules are:

- bb-aem-core - interfaces and some core classes
- bb-aem-64 - implementations for AEM 6.4

However there is no documentation except for javadocs and we are still in active development of this features so API can change or break before final release (we hope for december but I can't give solid date today)

**Comment by Shaihuludus** [comment]
Sorry my mistake. Branch for AEM API is 277-aem-author

**Comment by mkrzyzanowski** [comment]
All AEM features are now merged into `2.0.0-develop` branch - I've updated the README file.
